version: '3'
services:
  app:
    image: quizdocker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo/enis
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
      - ./test:/app/test
  mongo:
    image: mongo
    ports:
      - 27018:27017
